# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 634f515ffd922c7b7809c0885c1af56f86a99d0ded02c08b4dd5759287c46fcbf12dd905f18936bd11d38f0dffac8ef27b5a08f1f884653cf34cf5a1d15504ae

test:
  secret_key_base: 2dec224c6a1dbe120ecd21b62eefde06fa4d960337c40b3c672764f6699da01c1baf43d4b52e74e7c7cc6a5e2c6ca41042153af1d7c3058be646ab10008486d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
